/**
 * @file find-by-ids.test.ts
 * @module @stackra/nestjs-orm/__tests__/unit
 * @description Unit tests for the `findByIds()` and `findByForeignKey()` methods
 *   generated by `defineService()`. Verifies correct ordering, missing ID error
 *   handling, empty array behavior, and FK grouping.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ─── Mock Setup ───────────────────────────────────────────────────────────────

import 'reflect-metadata';

// Mock entity class with minimal metadata for defineService to read
function createMockEntityClass(name: string) {
  class MockEntity {}
  Object.defineProperty(MockEntity, 'name', { value: name });
  // ORM reads these metadata keys from the entity class
  Reflect.defineMetadata(
    'entity:definition',
    { name, tableName: name.toLowerCase() + 's' },
    MockEntity
  );
  // Traits stored on prototype
  Reflect.defineMetadata(Symbol.for('entity:traits'), [], MockEntity.prototype);
  Reflect.defineMetadata('entity:traits', [], MockEntity.prototype);
  // No stored fields
  Reflect.defineMetadata(Symbol.for('orm:stored'), [], MockEntity);
  return MockEntity;
}

// Mock repository
function createMockRepo(entities: any[] = []) {
  const em = {
    create: vi.fn(),
    persist: vi.fn(),
    flush: vi.fn(),
    remove: vi.fn(),
    assign: vi.fn(),
    findOne: vi.fn(),
    findOneOrFail: vi.fn(),
  };

  return {
    find: vi.fn().mockResolvedValue(entities),
    findOne: vi.fn(),
    count: vi.fn().mockResolvedValue(0),
    getEntityManager: vi.fn().mockReturnValue(em),
  };
}

// Import after mocks are set up
import { defineService } from '../../src/factories/crud-service.factory';

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('defineService() — findByIds()', () => {
  let Service: any;
  let repo: ReturnType<typeof createMockRepo>;

  beforeEach(() => {
    const Entity = createMockEntityClass('User');
    Service = defineService(Entity);
    repo = createMockRepo();
  });

  it('should return entities in the same order as input IDs', async () => {
    const entities = [
      { id: 'c', name: 'Charlie' },
      { id: 'a', name: 'Alice' },
      { id: 'b', name: 'Bob' },
    ];
    repo.find.mockResolvedValue(entities);

    const service = new Service(repo);
    const result = await service.findByIds(['a', 'b', 'c']);

    expect(result).toHaveLength(3);
    expect(result[0]).toEqual({ id: 'a', name: 'Alice' });
    expect(result[1]).toEqual({ id: 'b', name: 'Bob' });
    expect(result[2]).toEqual({ id: 'c', name: 'Charlie' });
  });

  it('should return Error for missing IDs', async () => {
    const entities = [
      { id: 'a', name: 'Alice' },
      // 'b' is missing
      { id: 'c', name: 'Charlie' },
    ];
    repo.find.mockResolvedValue(entities);

    const service = new Service(repo);
    const result = await service.findByIds(['a', 'b', 'c']);

    expect(result).toHaveLength(3);
    expect(result[0]).toEqual({ id: 'a', name: 'Alice' });
    expect(result[1]).toBeInstanceOf(Error);
    expect((result[1] as Error).message).toContain('b');
    expect(result[2]).toEqual({ id: 'c', name: 'Charlie' });
  });

  it('should return empty array for empty input', async () => {
    const service = new Service(repo);
    const result = await service.findByIds([]);

    expect(result).toEqual([]);
    expect(repo.find).not.toHaveBeenCalled();
  });

  it('should handle single ID', async () => {
    repo.find.mockResolvedValue([{ id: 'x', name: 'Xavier' }]);

    const service = new Service(repo);
    const result = await service.findByIds(['x']);

    expect(result).toHaveLength(1);
    expect(result[0]).toEqual({ id: 'x', name: 'Xavier' });
  });

  it('should handle duplicate IDs in input', async () => {
    repo.find.mockResolvedValue([{ id: 'a', name: 'Alice' }]);

    const service = new Service(repo);
    const result = await service.findByIds(['a', 'a', 'a']);

    expect(result).toHaveLength(3);
    expect(result[0]).toEqual({ id: 'a', name: 'Alice' });
    expect(result[1]).toEqual({ id: 'a', name: 'Alice' });
    expect(result[2]).toEqual({ id: 'a', name: 'Alice' });
  });

  it('should call repo.find with $in operator', async () => {
    repo.find.mockResolvedValue([]);

    const service = new Service(repo);
    await service.findByIds(['x', 'y', 'z']);

    expect(repo.find).toHaveBeenCalledWith({ id: { $in: ['x', 'y', 'z'] } }, expect.any(Object));
  });

  it('should return all Errors when no entities found', async () => {
    repo.find.mockResolvedValue([]);

    const service = new Service(repo);
    const result = await service.findByIds(['a', 'b']);

    expect(result).toHaveLength(2);
    expect(result[0]).toBeInstanceOf(Error);
    expect(result[1]).toBeInstanceOf(Error);
  });
});

describe('defineService() — findByForeignKey()', () => {
  let Service: any;
  let repo: ReturnType<typeof createMockRepo>;

  beforeEach(() => {
    const Entity = createMockEntityClass('Comment');
    Service = defineService(Entity);
    repo = createMockRepo();
  });

  it('should group entities by FK value', async () => {
    const entities = [
      { id: '1', post_id: 'p1', body: 'First' },
      { id: '2', post_id: 'p1', body: 'Second' },
      { id: '3', post_id: 'p2', body: 'Third' },
    ];
    repo.find.mockResolvedValue(entities);

    const service = new Service(repo);
    const result = await service.findByForeignKey('post_id', ['p1', 'p2', 'p3']);

    expect(result.get('p1')).toHaveLength(2);
    expect(result.get('p2')).toHaveLength(1);
    expect(result.get('p3')).toHaveLength(0);
  });

  it('should return empty map for empty input', async () => {
    const service = new Service(repo);
    const result = await service.findByForeignKey('post_id', []);

    expect(result.size).toBe(0);
    expect(repo.find).not.toHaveBeenCalled();
  });

  it('should return empty arrays for FKs with no matches', async () => {
    repo.find.mockResolvedValue([]);

    const service = new Service(repo);
    const result = await service.findByForeignKey('post_id', ['p1', 'p2']);

    expect(result.get('p1')).toEqual([]);
    expect(result.get('p2')).toEqual([]);
  });

  it('should query with $in on the FK field', async () => {
    repo.find.mockResolvedValue([]);

    const service = new Service(repo);
    await service.findByForeignKey('author_id', ['u1', 'u2']);

    expect(repo.find).toHaveBeenCalledWith(
      { author_id: { $in: ['u1', 'u2'] } },
      expect.any(Object)
    );
  });

  it('should handle entities with same FK pointing to different IDs', async () => {
    const entities = [
      { id: '1', user_id: 'u1', content: 'a' },
      { id: '2', user_id: 'u1', content: 'b' },
      { id: '3', user_id: 'u1', content: 'c' },
    ];
    repo.find.mockResolvedValue(entities);

    const service = new Service(repo);
    const result = await service.findByForeignKey('user_id', ['u1']);

    expect(result.get('u1')).toHaveLength(3);
  });
});
