/**
 * @file field-schema.interface.ts
 * @module @stackra/orm/src/interfaces
 * @description IFieldSchema interface.
 */

/**
 * Single field schema.
 */
export interface IFieldSchema {
  /** Field name (property key). */
  name: string;
  /** Portable type (string, number, boolean, date, json, uuid, enum). */
  type: string;
  /** Whether the field allows null. */
  nullable: boolean;
  /** Default value (if any). */
  default?: unknown;
  /** Enum values (for enum type). */
  enum?: string[];
  /** Whether the field is indexed. */
  index: boolean;
  /** Whether the field has a unique constraint. */
  unique: boolean;
  /** Whether this is the primary key. */
  primary: boolean;
  /** Whether this field is auto-generated (id, timestamps, etc). */
  autoGenerated: boolean;
}
