/**
 * @file index.ts
 * @module @stackra/nestjs-health/constants
 * @description Barrel export for health constants (internal tokens and defaults).
 *
 * Public constants (HEALTH_EVENTS, HEALTH_INDICATOR_METADATA_KEY) live in
 * @stackra/contracts and are re-exported from the package root index.ts.
 */
export { HEALTH_MODULE_OPTIONS, HEALTH_RESULT_STORE, HEALTH_METRICS } from './tokens.constant';

export {
  DEFAULT_BASE_PATH,
  DEFAULT_HEAP_THRESHOLD,
  DEFAULT_RSS_THRESHOLD,
  DEFAULT_DISK_PATH,
  DEFAULT_DISK_THRESHOLD_PERCENT,
  DEFAULT_INDICATOR_TIMEOUT,
  DEFAULT_CONCURRENCY,
  MIN_CONCURRENCY,
  MAX_CONCURRENCY,
  DEFAULT_RETRY_MAX_ATTEMPTS,
  DEFAULT_RETRY_DELAY,
  DEFAULT_COOLDOWN_SECONDS,
  MIN_COOLDOWN_SECONDS,
  MAX_COOLDOWN_SECONDS,
  DEFAULT_STORE_CAPACITY,
  MIN_STORE_CAPACITY,
  MAX_STORE_CAPACITY,
  MIN_SCHEDULE_INTERVAL,
  DEFAULT_EVENT_LOOP_LAG_THRESHOLD,
  DEFAULT_EVENT_LOOP_RESOLUTION,
  DEFAULT_CERT_WARNING_DAYS,
  DEFAULT_CERT_CRITICAL_DAYS,
  DEFAULT_HTTP_PING_TIMEOUT,
  MAX_HTTP_REDIRECT_HOPS,
  DEFAULT_DNS_TIMEOUT,
  DEGRADATION_RATIO,
  MAX_INDICATOR_NAME_LENGTH,
  INDICATOR_NAME_PATTERN,
} from './defaults.constant';
